main: net.flutterflies.waterless.Waterless
version: 1.4
name: WaterlessRedstone
description: Makes Redstone unaffected by water
author: Ashrynn Macke|Flutterflies
website: www.flutterflies.net

commands:
  wlrblocks:
    description: Get a list of all blocks currently enabled by Waterless Redstone
    usage: /wlrblocks
    aliases: [waterless, wlr]

permissions:
 wlr.*:
   children:
     wlr.blocks:
       default: true
       description: Give access to the wlr command